name: Socket Security Scan

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  socket:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Socket Security Scan
        uses: socketdotdev/socket-github-action@v2
        with:
          api-key: ${{ secrets.SOCKET_SECURITY_API_KEY }}
